[auth]
redirect_uri = "http://localhost:8000/oauth2callback"
cookie_secret = "p6SuMm1x7mI4kvK1_l77AeFOIFh_CGDQjDhj63CRj48"
client_id = "782334707710-ghsf0df7ljrkdavemfmntav9ok2i1aav.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
